name: open-pulse-quickstart
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - numba
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - ipykernel>=7.0.1
  - xarray
  - pytz
  - pyparsing
  - pip
  - pip:
      # For neo4j environment
      - deepsmiles
      - rdkit
      - adjusttext>=1.3.0
      - python-dotenv>=0.9.9
      - matplotlib>=3.10.7
      - neo4j>=6.0.2
      - networkx>=3.4.2
      - numpy>=2.2.6
      - pandas>=2.3.3
      - pydantic>=2.12.1

      # For Tentris notebook environment
      - tentris
      - rdflib

prefix: /opt/conda
